#!/bin/bash
index_array=("min_fidelity_throughputs" "min_fidelity_fail-finished_ratio" "new_request_cnt_throughputs"\
             "num_of_node_throughputs" "new_request_cnt_use_memory_ratio" "new_request_cnt_use_channel_ratio"\
            "new_request_cnt_runtime" "min_fidelity_encode_ratio" "path_length_encode_cnt")
#index_array=("min_fidelity_encode_ratio")

for i in ${index_array[@]}
do
    #echo $i
    #cat $i.ans
	cp  11031737/ans/$i.ans ../use/tmp/
done