#!/bin/bash
index_array=("min_fidelity_throughputs" "new_request_cnt_throughputs" "num_of_node_throughputs" "min_fidelity_fail-finished_ratio" "new_request_cnt_use_memory_ratio" "new_request_cnt_use_channel_ratio" "new_request_cnt_runtime")
#index_array=("min_fidelity_encode_ratio")

for i in ${index_array[@]}
do
    echo $i
    cat $i.ans
	cp $i.ans ../../../use
done